version: '3'
services:
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3333:3000
    networks:
      - grafana-net
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    networks:
      - grafana-net

networks:
  grafana-net:

